"""
Document generation tool — REAL, not a stub.

Builds an actual .docx approval note with python-docx, following the
required sections from the plant's approval-note workflow reference.

Owner: Track B.
"""
import os
import re
from datetime import datetime

from docx import Document
from docx.shared import Pt, RGBColor

from .. import config


def _clean_xml_string(text: str) -> str:
    if not text:
        return ""
    # Strip illegal XML 1.0 control characters (preserves tab, newline, carriage return)
    return re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x84\x86-\x9f]", "", str(text)).strip()


# Severity keywords, highest first — used for the severity summary line
_SEVERITY_RULES = [
    ("Critical", ["leak detected", "critical", "immediate"]),
    ("Major", ["corrosion", "crack", "exceed", "deviation"]),
    ("Minor", ["wear", "discoloration", "minor"]),
]


def _infer_severity(findings: list[str]) -> str:
    joined = " ".join(findings).lower()
    for level, keywords in _SEVERITY_RULES:
        if any(k in joined for k in keywords):
            return level
    return "Observation"


def draft_approval_note(source_name: str, findings: list[str], task_id: str) -> str:
    doc = Document()

    title = doc.add_heading("Approval Note", level=1)
    title.runs[0].font.color.rgb = RGBColor(0x1C, 0x5D, 0x99)

    clean_source = _clean_xml_string(source_name)
    clean_task = _clean_xml_string(task_id)

    meta = doc.add_paragraph()
    meta.add_run("Generated by: UrjaKavach Sovereign AI Workbench\n").bold = True
    meta.add_run(f"Source document: {clean_source}\n")
    meta.add_run(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
    meta.add_run(f"Task ID: {clean_task}")

    doc.add_heading("Key Findings & Observations", level=2)
    clean_findings = [_clean_xml_string(f) for f in findings if _clean_xml_string(f)]
    if clean_findings:
        for f in clean_findings:
            doc.add_paragraph(f, style="List Bullet")
    else:
        doc.add_paragraph("Document processed successfully.")

    doc.add_heading("Assessment / Status", level=2)
    doc.add_paragraph(f"Status / Severity: {_infer_severity(findings)}")

    doc.add_heading("Review & Recommendation", level=2)
    doc.add_paragraph(
        "Key points and findings above are prepared automatically from the source document. "
        "Verified and generated entirely on-premise."
    )

    doc.add_heading("Sign-off", level=2)
    doc.add_paragraph("Responsible Engineer: ______________________    Date: ____________")

    footer = doc.add_paragraph()
    run = footer.add_run(
        "Generated entirely on-premise. No data left the facility."
    )
    run.italic = True
    run.font.size = Pt(9)

    out_path = os.path.join(config.OUTPUTS_DIR, f"approval_note_{task_id}.docx")
    doc.save(out_path)
    return out_path
